naruto = {

    1: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/1.mp4",
    2: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/2.mp4",
    3: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/3.mp4",
    4: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/4.mp4",
    5: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/5.mp4",
    6: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/6.mp4",
    7: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/7.mp4",
    8: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/8.mp4",
    9: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/9.mp4",

    10: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/10.mp4",
    11: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/11.mp4",
    12: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/12.mp4",
    13: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/13.mp4",
    14: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/14.mp4",
    15: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/15.mp4",
    16: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/16.mp4",
    17: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/17.mp4",
    18: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/18.mp4",
    19: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/19.mp4",

    20: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/20.mp4",
    21: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/21.mp4",
    22: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/22.mp4",
    23: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/23.mp4",
    24: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/24.mp4",
    25: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/25.mp4",
    26: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/26.mp4",
    27: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/27.mp4",
    28: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/28.mp4",
    29: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/29.mp4",

    30: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/30.mp4",
    31: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/31.mp4",
    32: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/32.mp4",
    33: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/33.mp4",
    34: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/34.mp4",
    35: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/35.mp4",
    36: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/36.mp4",
    37: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/37.mp4",
    38: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/38.mp4",
    39: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/39.mp4",

    40: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/40.mp4",
    41: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/41.mp4",
    42: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/42.mp4",
    43: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/43.mp4",
    44: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/44.mp4",
    45: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/45.mp4",
    46: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/46.mp4",
    47: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/47.mp4",
    48: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/48.mp4",
    49: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/49.mp4",

    50: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/50.mp4",
    51: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/51.mp4",
    52: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/52.mp4",
    53: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/53.mp4",
    54: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/54.mp4",
    55: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/55.mp4",
    56: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/56.mp4",
    57: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/57.mp4",
    58: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/58.mp4",
    59: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/59.mp4",

    60: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/60.mp4",
    61: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/61.mp4",
    62: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/62.mp4",
    63: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/63.mp4",
    64: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/64.mp4",
    65: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/65.mp4",
    66: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/66.mp4",
    67: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/67.mp4",
    68: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/68.mp4",
    69: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/69.mp4",

    70: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/70.mp4",
    71: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/71.mp4",
    72: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/72.mp4",
    73: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/73.mp4",
    74: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/74.mp4",
    75: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/75.mp4",
    76: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/76.mp4",
    77: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/77.mp4",
    78: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/78.mp4",
    79: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/79.mp4",

    80: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/80.mp4",
    81: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/81.mp4",
    82: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/82.mp4",
    83: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/83.mp4",
    84: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/84.mp4",
    85: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/85.mp4",
    86: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/86.mp4",
    87: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/87.mp4",
    88: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/88.mp4",
    89: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/89.mp4",

    90: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/90.mp4",
    91: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/91.mp4",
    92: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/92.mp4",
    93: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/93.mp4",
    94: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/94.mp4",
    95: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/95.mp4",
    96: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/96.mp4",
    97: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/97.mp4",
    98: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/98.mp4",
    99: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/99.mp4",

    100: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/100.mp4",
    101: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/101.mp4",
    102: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/102.mp4",
    103: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/103.mp4",
    104: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/104.mp4",
    105: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/105.mp4",
    106: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/106.mp4",
    107: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/107.mp4",
    108: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/108.mp4",
    109: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/109.mp4",

    110: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/110.mp4",
    111: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/111.mp4",
    112: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/112.mp4",
    113: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/113.mp4",
    114: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/114.mp4",
    115: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/115.mp4",
    116: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/116.mp4",
    117: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/117.mp4",
    118: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/118.mp4",
    119: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/119.mp4",

    120: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/120.mp4",
    121: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/121.mp4",
    122: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/122.mp4",
    123: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/123.mp4",
    124: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/124.mp4",
    125: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/125.mp4",
    126: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/126.mp4",
    127: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/127.mp4",
    128: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/128.mp4",
    129: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/129.mp4",

    130: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/130.mp4",
    131: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/131.mp4",
    132: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/132.mp4",
    133: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/133.mp4",
    134: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/134.mp4",
    135: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/135.mp4",
    136: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/136.mp4",
    137: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/137.mp4",
    138: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/138.mp4",
    139: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/139.mp4",

    140: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/140.mp4",
    141: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/141.mp4",
    142: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/142.mp4",
    143: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/143.mp4",
    144: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/144.mp4",
    145: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/145.mp4",
    146: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/146.mp4",
    147: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/147.mp4",
    148: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/148.mp4",
    149: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/149.mp4",

    150: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/150.mp4",
    151: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/151.mp4",
    152: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/152.mp4",
    153: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/153.mp4",
    154: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/154.mp4",
    155: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/155.mp4",
    156: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/156.mp4",
    157: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/157.mp4",
    158: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/158.mp4",
    159: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/159.mp4",

    160: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/160.mp4",
    161: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/161.mp4",
    162: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/162.mp4",
    163: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/163.mp4",
    164: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/164.mp4",
    165: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/165.mp4",
    166: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/166.mp4",
    167: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/167.mp4",
    168: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/168.mp4",
    169: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/169.mp4",

    170: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/170.mp4",
    171: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/171.mp4",
    172: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/172.mp4",
    173: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/173.mp4",
    174: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/174.mp4",
    175: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/175.mp4",
    176: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/176.mp4",
    177: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/177.mp4",
    178: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/178.mp4",
    179: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/179.mp4",

    180: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/180.mp4",
    181: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/181.mp4",
    182: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/182.mp4",
    183: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/183.mp4",
    184: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/184.mp4",
    185: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/185.mp4",
    186: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/186.mp4",
    187: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/187.mp4",
    188: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/188.mp4",
    189: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/189.mp4",

    190: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/190.mp4",
    191: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/191.mp4",
    192: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/192.mp4",
    193: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/193.mp4",
    194: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/194.mp4",
    195: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/195.mp4",
    196: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/196.mp4",
    197: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/197.mp4",
    198: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/198.mp4",
    199: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/199.mp4",

    200: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/200.mp4",
    201: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/201.mp4",
    202: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/202.mp4",
    203: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/203.mp4",
    204: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/204.mp4",
    205: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/205.mp4",
    206: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/206.mp4",
    207: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/207.mp4",
    208: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/208.mp4",
    209: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/209.mp4",

    210: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/210.mp4",
    211: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/211.mp4",
    212: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/212.mp4",
    213: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/213.mp4",
    214: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/214.mp4",
    215: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/215.mp4",
    216: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/216.mp4",
    217: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/217.mp4",
    218: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/218.mp4",
    219: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/219.mp4",

    220: "https://videos.animesgratisbr.com/pubfolder/animes/Naruto/220.mp4",
}
